[logs]
dir_name = "logs"
file_name = "recsys_framework_extensions.log"
formatter = "%(process)d|%(asctime)s|%(levelname)s|%(module)s|%(funcName)s|%(lineno)d|%(message)s"

[tool.mypy]
python_version = "~3.9"
ignore_missing_imports = true

[tool.poetry]
name = "recsys_framework_extensions"
version = "0.1.0"
description = ""
authors = ["Fernando Benjamín PÉREZ MAURERA <fperezmaurera@gmail.com>"]
packages = [
    { include = "recsys_framework_extensions" }, # Include the recsys_framework_extensions folder as a package.
]
exclude = [
    { path = "build/*" },
]

[tool.poetry.dependencies]
python = "~3.9"
dask = { extras = ["complete"], version = "^2022.2.1" }
attrs = "^21.4.0"
holoviews = "^1.14.8"
numpy = "^1.22.2"
pandas = "^1.4.1"

[tool.poetry.dev-dependencies]
mypy = "^0.931"
types-toml = "^0.10.4"

[tool.poetry.build]
generate-setup-file = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
